### ISSUE TITLE
AttributeError: 'module' object has no attribute 'init'

### ISSUE THREAD

**Issue by HTaCheng** [craymichael/CNN_LCD#7] opened 2020-07-02 01:53 UTC
An error occurred when I initialized the overfeat network, how can I solve this

**Comment by craymichael** [comment] 2020-07-02 15:27
Can you share the traceback? I can't reproduce.

**Comment by craymichael** [comment] 2020-07-02 15:30
Looks like this is likely a problem induced my not having overfeat installed properly. Closing per #8 for now.

**Closed by craymichael** 2020-07-02 15:30 UTC
